# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx293rA2OXHF49fqybjAdZY5Mu7MQ6kl
"""
pip install pymupdf

import gradio as gr
import fitz  # PyMuPDF for PDF extraction
from transformers import AutoTokenizer, AutoModelForCausalLM

# Load IBM Granite model (replace with actual IBM Granite model name if different)
tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

def extract_text_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    text = ""
    for page in doc:
        text += page.get_text()
    return text

def smart_sdlc_run(pdf_file, prompt, sdlc_phase, language, framework, action):
    input_text = ""
    if pdf_file:
        input_text = extract_text_from_pdf(pdf_file.name)
    elif prompt:
        input_text = prompt
    else:
        return "Please upload a PDF or enter a prompt."

    full_prompt = f"{action} for {sdlc_phase} using {language} and {framework}: {input_text}"

    inputs = tokenizer(full_prompt, return_tensors="pt")
    outputs = model.generate(inputs["input_ids"], max_length=200, num_return_sequences=1)
    result = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return result

with gr.Blocks(css="""
.gradio-container {
  background-color: orange;
  padding: 20px;
  border-radius: 10px;
}
.textbox-bordered {
  border: 4px solid green;  /* Dark blue thick border */
  border-radius: 6px;
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.2);
}
.custom-run-button {
  background-color: #4CAF50 !important;  /* Green button */
  color: white !important;
  font-weight: bold;
  border-radius: 8px;
  padding: 10px 20px;
}
.small-file-btn {
  max-width: 150px;
  max-height: 105px;
  border-radius: 8px;
  border: 150px solid green;
}
""") as demo:
    gr.Markdown("🚀 **SmartSDLC: AI-Enhanced Software Development Lifecycle**")

    with gr.Row():
        output_text = gr.Textbox(label="Generated Output", lines=10, elem_classes=["textbox-bordered"])

    with gr.Row():
        file_input = gr.File(label="Upload PDF (optional)", file_types=['.pdf'], type="filepath", elem_classes=["small-file-btn"])
        prompt_input = gr.Textbox(label="Or enter a prompt", lines=2)

    with gr.Row():
        sdlc_phase = gr.Dropdown(choices=["Requirements", "Design", "Development", "Testing", "Deployment"], value="Requirements", label="SDLC Phase")

        action = gr.Radio(choices=["Extract Requirements", "Generate Code"], value="Extract Requirements", label="Action")

    run_button = gr.Button("Run SmartSDLC", elem_classes=["custom-run-button"])

    run_button.click(
        smart_sdlc_run,
        inputs=[file_input, prompt_input, sdlc_phase, action],
        outputs=output_text
    )

demo.launch(debug=True)
